### ISSUE TITLE
Transfer repository to coq-community for maintenance? 

### ISSUE THREAD

**Issue by anton-trunov** [coq-community/regexp-Brzozowski#2]
Dear Vincent,

Since this repository is unmaintained, would you be willing to transfer it to coq-community?
It's an organization of Coq enthusiasts who collaboratively develop or maintain important Coq projects. 
If you are interested, you can find more information here: https://github.com/coq-community/manifesto.

Even if transfer the ownership you and Thierry will still be credited as the authors, see https://github.com/coq-community/lemma-overloading, for example.

One thing we usually ask (but this is not a prerequisite) -- to relicense the code from GPL, which was not developed with proof assistants in mind, to a more permissive MIT license or something like that.

Please let me know what you think.

Best regards,
Anton Trunov
coq-community maintainer

**Comment by vsiles** [comment]
I think that is a great idea, as I don't have the bandwidth to maintain in on a regular basis. No problem about the license. I'll read about the process to transfer it later this week and will keep you updated.

**Comment by anton-trunov** [comment]
Great! Thank you for your quick response. I'll open an issue at the manifesto repo to track it there (that's the usual process) and tag you in it. Feel free to ping me or any other coq-community maintainers if you have any questions. If you feel like having a more online conversation, you are welcome to join us on Coq's Zulip chat: https://coq.zulipchat.com/#narrow/stream/237663-coq-community-devs.20.26.20users (login required).

**Comment by anton-trunov** [comment]
The transfer is done, closing.
